language: node_js
cache:
  directories:
    - node_modules
env:
  - MONGO_URI=mongodb://127.0.0.1:27017/netsblox-tests ENV=test DEBUG=netsblox:test*
services:
  - mongodb
node_js:
  - 12.14.1
install:
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - sudo apt-get update && sudo apt-get install iproute2 g++ -y
script:
  - npm test && npm run test-client
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
